[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[build]
target = "x86_64-unknown-none"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
strip = true
panic = "abort"

[build-dependencies]
cc = "1.2.12"
